import{CommandHistory,createPage,createProject,deepClone,migrateProject,uid}from'./document-model.js';
import{getProject,listProjects,putProject,removeProject}from'./project-store.js';

const canvas=document.getElementById('mangaCanvas'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;
const characterImage=new Image();characterImage.src='akira.png';const spriteCache=new Map();
let project,zoom=.82,selectedIds=new Set(),drag=null,toastTimer,saveTimer,controlBefore=null,guides=[];
const histories=new Map();
const page=()=>project.pages.find(item=>item.id===project.activePageId)||project.pages[0];
const history=()=>{if(!histories.has(page().id))histories.set(page().id,new CommandHistory());return histories.get(page().id)};
const current=()=>[...selectedIds].map(id=>page().elements.find(element=>element.id===id)).filter(Boolean).at(-1);

function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
function setSaveState(message){document.getElementById('saveState').textContent=message}
function panels(){const layout=page().layout;if(layout==='two')return[{x:25,y:25,w:550,h:360},{x:25,y:405,w:550,h:370}];if(layout==='four')return[{x:25,y:25,w:265,h:365},{x:310,y:25,w:265,h:365},{x:25,y:410,w:265,h:365},{x:310,y:410,w:265,h:365}];return[{x:25,y:25,w:550,h:315},{x:25,y:360,w:260,h:415},{x:305,y:360,w:270,h:415}]}

function drawBackground(panel,index){ctx.save();ctx.beginPath();ctx.rect(panel.x,panel.y,panel.w,panel.h);ctx.clip();const bg=page().background;
  if(bg==='city'){const gradient=ctx.createLinearGradient(0,panel.y,0,panel.y+panel.h);gradient.addColorStop(0,index?'#d6d3ca':'#40434b');gradient.addColorStop(1,index?'#8b8d91':'#9b8760');ctx.fillStyle=gradient;ctx.fillRect(panel.x,panel.y,panel.w,panel.h);ctx.fillStyle='#202126';for(let x=panel.x-10;x<panel.x+panel.w;x+=48){const height=70+(x*13%130);ctx.fillRect(x,panel.y+panel.h-height,38,height);ctx.fillStyle='#e1b64a';for(let y=panel.y+panel.h-height+14;y<panel.y+panel.h-12;y+=22){ctx.fillRect(x+7,y,7,6);ctx.fillRect(x+22,y,7,6)}ctx.fillStyle='#202126'}}
  else if(bg==='dots'){ctx.fillStyle='#eee';ctx.fillRect(panel.x,panel.y,panel.w,panel.h);ctx.fillStyle='#777';for(let y=panel.y;y<panel.y+panel.h;y+=8)for(let x=panel.x+(y%16?4:0);x<panel.x+panel.w;x+=8){ctx.beginPath();ctx.arc(x,y,1.7,0,Math.PI*2);ctx.fill()}}
  else if(bg==='speed'){ctx.fillStyle='#efeee9';ctx.fillRect(panel.x,panel.y,panel.w,panel.h);ctx.strokeStyle='#555';ctx.lineWidth=1;for(let i=0;i<50;i++){ctx.beginPath();ctx.moveTo(panel.x-20,panel.y+(i*37)%panel.h);ctx.lineTo(panel.x+panel.w+30,panel.y+(i*37)%panel.h-80);ctx.stroke()}}
  else if(bg==='burst'){ctx.fillStyle='#eee';ctx.fillRect(panel.x,panel.y,panel.w,panel.h);ctx.translate(panel.x+panel.w/2,panel.y+panel.h/2);for(let i=0;i<36;i++){ctx.rotate(Math.PI/18);ctx.beginPath();ctx.moveTo(35,-2);ctx.lineTo(Math.max(panel.w,panel.h),-7);ctx.lineTo(Math.max(panel.w,panel.h),7);ctx.closePath();ctx.fillStyle=i%3===0?'#777':'#d3d1ca';ctx.fill()}}
  else{ctx.fillStyle='#faf9f4';ctx.fillRect(panel.x,panel.y,panel.w,panel.h)}ctx.restore();ctx.strokeStyle='#111';ctx.lineWidth=6;ctx.strokeRect(panel.x,panel.y,panel.w,panel.h)}

function imageFor(element){if(!element.sprite)return characterImage;if(!spriteCache.has(element.id)){const image=new Image();image.onload=render;image.src=element.sprite;spriteCache.set(element.id,image)}return spriteCache.get(element.id)}
function wrapText(text,maxWidth,font){ctx.font=font;const lines=[];for(const paragraph of String(text||'').split('\n')){let line='';for(const word of paragraph.split(' ')){const candidate=line?`${line} ${word}`:word;if(ctx.measureText(candidate).width>maxWidth&&line){lines.push(line);line=word}else line=candidate}lines.push(line)}return lines}
function drawCharacter(element){ctx.save();ctx.translate(element.x,element.y);ctx.rotate(element.rotation*Math.PI/180);ctx.scale((element.flip?-1:1)*element.scale,element.scale);if(element.expression==='angry')ctx.filter='contrast(1.22) saturate(.8)';if(element.expression==='happy')ctx.filter='saturate(1.25) brightness(1.06)';if(element.expression==='surprised')ctx.filter='brightness(1.13) contrast(1.08)';const image=imageFor(element);if(image.complete)ctx.drawImage(image,-element.w/2,-element.h/2,element.w,element.h);ctx.restore()}
function drawTextElement(element){ctx.save();ctx.translate(element.x,element.y);ctx.rotate(element.rotation*Math.PI/180);ctx.scale((element.flip?-1:1)*element.scale,element.scale);const{w,h}=element;
  if(element.type==='bubble'||element.type==='thought'){ctx.fillStyle='#fff';ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(element.type==='thought'){ctx.beginPath();ctx.arc(w*.2,h*.52,10,0,Math.PI*2);ctx.arc(w*.27,h*.68,5,0,Math.PI*2);ctx.fill();ctx.stroke()}else{ctx.beginPath();ctx.moveTo(w*.2,h*.38);ctx.lineTo(w*.36,h*.72);ctx.lineTo(w*.04,h*.45);ctx.fill();ctx.stroke()}}
  if(element.type==='shout'){ctx.fillStyle='#fff';ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<24;i++){const angle=i*Math.PI/12,radius=i%2?Math.min(w,h)*.37:Math.min(w,h)*.55;const x=Math.cos(angle)*radius,y=Math.sin(angle)*radius;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke()}
  if(element.type==='caption'){ctx.fillStyle='#111';ctx.fillRect(-w/2,-h/2,w,h)}const fx=element.type==='fx';ctx.fillStyle=element.type==='caption'?'#fff':fx?'#f3b61f':'#111';ctx.strokeStyle=fx?'#111':'transparent';ctx.lineWidth=fx?7:0;ctx.textAlign='center';ctx.textBaseline='middle';const size=element.fontSize||24;ctx.font=`${fx?'900 italic':'800'} ${size}px Arial`;const lines=wrapText(element.text,w-24,ctx.font);lines.forEach((line,index)=>{const y=(index-(lines.length-1)/2)*size*1.08;if(fx)ctx.strokeText(line,0,y);ctx.fillText(line,0,y)});ctx.restore()}
function drawElement(element){const panel=Number.isInteger(element.panelId)?panels()[element.panelId]:null;ctx.save();if(panel){ctx.beginPath();ctx.rect(panel.x+3,panel.y+3,panel.w-6,panel.h-6);ctx.clip()}element.type==='character'?drawCharacter(element):drawTextElement(element);ctx.restore()}
function localPoint(point,element){const angle=-element.rotation*Math.PI/180,dx=point.x-element.x,dy=point.y-element.y;return{x:(dx*Math.cos(angle)-dy*Math.sin(angle))/element.scale,y:(dx*Math.sin(angle)+dy*Math.cos(angle))/element.scale}}
function hitElement(point,element){const local=localPoint(point,element);return Math.abs(local.x)<=element.w/2&&Math.abs(local.y)<=element.h/2}
function handleAt(point,element){const local=localPoint(point,element),corners=[[-element.w/2,-element.h/2],[element.w/2,-element.h/2],[-element.w/2,element.h/2],[element.w/2,element.h/2]];if(Math.hypot(local.x,local.y+element.h/2+28)<13)return'rotate';return corners.some(([x,y])=>Math.hypot(local.x-x,local.y-y)<12)?'scale':null}
function drawSelection(element,primary){ctx.save();ctx.translate(element.x,element.y);ctx.rotate(element.rotation*Math.PI/180);ctx.scale(element.scale,element.scale);ctx.strokeStyle=element.locked?'#ef6b57':'#f3b61f';ctx.lineWidth=2/element.scale;ctx.setLineDash([7/element.scale,5/element.scale]);ctx.strokeRect(-element.w/2,-element.h/2,element.w,element.h);ctx.setLineDash([]);if(primary){ctx.fillStyle='#f3b61f';for(const[x,y]of[[-element.w/2,-element.h/2],[element.w/2,-element.h/2],[-element.w/2,element.h/2],[element.w/2,element.h/2]])ctx.fillRect(x-5/element.scale,y-5/element.scale,10/element.scale,10/element.scale);ctx.beginPath();ctx.arc(0,-element.h/2-28,6/element.scale,0,Math.PI*2);ctx.fill()}ctx.restore()}
function render(withSelection=true){ctx.clearRect(0,0,W,H);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);panels().forEach(drawBackground);page().elements.filter(element=>element.visible!==false).forEach(drawElement);if(withSelection)[...selectedIds].forEach((id,index,array)=>{const element=page().elements.find(item=>item.id===id);if(element?.visible)drawSelection(element,index===array.length-1)});if(guides.length){ctx.save();ctx.strokeStyle='#55d6be';ctx.lineWidth=1;ctx.setLineDash([4,4]);for(const guide of guides){ctx.beginPath();guide.axis==='x'?(ctx.moveTo(guide.value,0),ctx.lineTo(guide.value,H)):(ctx.moveTo(0,guide.value),ctx.lineTo(W,guide.value));ctx.stroke()}ctx.restore()}}

function record(label,before){const after=JSON.stringify(page());history().push({label,before,after});afterChange()}
function mutate(label,operation){const before=JSON.stringify(page());operation();record(label,before)}
function replacePage(next){const index=project.pages.findIndex(item=>item.id===project.activePageId);project.pages[index]=next;project.activePageId=next.id;selectedIds.clear();afterChange()}
function afterChange(){project.updatedAt=new Date().toISOString();render();updateInspector();renderLayers();renderPageRail();scheduleSave()}
function scheduleSave(){setSaveState('Guardando…');clearTimeout(saveTimer);saveTimer=setTimeout(saveProject,350)}
async function saveProject(){try{render(false);page().thumbnail=canvas.toDataURL('image/jpeg',.55);render();await putProject(project);localStorage.setItem('manga-studio-active-project',project.id);setSaveState('Guardado ✓')}catch(error){console.error(error);setSaveState('Error al guardar');showToast('No se pudo guardar el proyecto')}}

function addElement(type){mutate('Añadir elemento',()=>{const id=uid(type);let element;if(type==='character')element={id,type,name:'Akira',x:300,y:420,w:260,h:410,scale:.82,rotation:0,flip:false,pose:'neutral',expression:'neutral'};else{const meta={bubble:['Diálogo','¿Qué está pasando?',230,110,23],shout:['Grito','¡DETENTE!',220,150,29],thought:['Pensamiento','Tengo un mal presentimiento…',235,125,21],caption:['Narración','MIENTRAS TANTO…',250,62,19],fx:['Efecto','¡BAM!',210,100,46]}[type];element={id,type,name:meta[0],text:meta[1],x:300,y:210,w:meta[2],h:meta[3],fontSize:meta[4],scale:1,rotation:0,flip:false}}Object.assign(element,{visible:true,locked:false,panelId:panelAt(element.x,element.y)});page().elements.push(element);selectedIds=new Set([id])});showToast(type==='character'?'Personaje añadido':'Elemento añadido')}
function panelAt(x,y){return panels().findIndex(panel=>x>=panel.x&&x<=panel.x+panel.w&&y>=panel.y&&y<=panel.y+panel.h)}
function removeSelected(){if(!selectedIds.size)return;mutate('Eliminar elementos',()=>page().elements=page().elements.filter(element=>!selectedIds.has(element.id)));selectedIds.clear();afterChange();showToast('Elemento eliminado')}

function updateInspector(){const element=current(),count=selectedIds.size;document.getElementById('selectionName').textContent=count>1?`${count} elementos`:element?.name||'Página';document.getElementById('characterControls').hidden=!element||element.type!=='character'||count>1;document.getElementById('textControls').hidden=!element||element.type==='character'||count>1;document.getElementById('transformControls').hidden=!element;if(!element)return;document.getElementById('scaleRange').value=Math.round(element.scale*100);document.getElementById('rotateRange').value=element.rotation||0;if(element.type==='character'){document.getElementById('expressionSelect').value=element.expression;document.querySelectorAll('#poseControl button').forEach(button=>button.classList.toggle('active',button.dataset.pose===element.pose))}else{document.getElementById('textInput').value=element.text;document.getElementById('fontSize').value=element.fontSize;document.getElementById('fontSizeOut').value=element.fontSize}}
function selectLayer(element){const grouped=element.groupId?page().elements.filter(item=>item.groupId===element.groupId):[element];selectedIds=new Set(grouped.map(item=>item.id));render();updateInspector();renderLayers()}
function renderLayers(){const list=document.getElementById('layerList');list.innerHTML='';[...page().elements].reverse().forEach(element=>{const row=document.createElement('div');row.className='layer-row'+(selectedIds.has(element.id)?' active':'');const select=document.createElement('button'),visible=document.createElement('button'),locked=document.createElement('button');select.className='layer-select';select.textContent=(element.groupId?'◆ ':'')+element.name;select.title='Seleccionar · doble clic para renombrar';visible.className=locked.className='layer-state';visible.textContent=element.visible?'◉':'○';visible.title='Mostrar u ocultar';locked.textContent=element.locked?'🔒':'◇';locked.title='Bloquear o desbloquear';select.onclick=()=>selectLayer(element);select.ondblclick=()=>{const name=prompt('Nombre de la capa',element.name);if(name?.trim())mutate('Renombrar capa',()=>element.name=name.trim())};visible.onclick=()=>mutate('Visibilidad de capa',()=>element.visible=!element.visible);locked.onclick=()=>mutate('Bloqueo de capa',()=>element.locked=!element.locked);row.append(select,visible,locked);list.append(row)})}
function renderPageRail(){document.getElementById('pageTitle').textContent=page().name;const rail=document.getElementById('pageRail');rail.innerHTML='';project.pages.forEach((item,index)=>{const button=document.createElement('button');button.className='page-card'+(item.id===project.activePageId?' active':'');button.innerHTML=item.thumbnail?`<img src="${item.thumbnail}" alt=""><span>${index+1}</span>`:`<i></i><span>${index+1}</span>`;button.title=item.name;button.onclick=async()=>{if(item.id===project.activePageId)return;await saveProject();project.activePageId=item.id;selectedIds.clear();syncPageControls();afterChange()};rail.append(button)});const add=document.createElement('button');add.className='page-add';add.textContent='＋';add.title='Añadir página';add.onclick=addPage;rail.append(add)}
function syncPageControls(){document.querySelectorAll('.layout-option').forEach(button=>button.classList.toggle('active',button.dataset.layout===page().layout));document.getElementById('backgroundSelect').value=page().background;render();updateInspector();renderLayers();renderPageRail()}

function addPage(){const next=createPage(project.pages.length);project.pages.push(next);project.activePageId=next.id;selectedIds.clear();afterChange();showToast('Página añadida')}
function duplicatePage(){const copy=deepClone(page());copy.id=uid('page');copy.name=`${page().name} copia`;copy.elements.forEach(element=>element.id=uid(element.type));project.pages.splice(project.pages.indexOf(page())+1,0,copy);project.activePageId=copy.id;selectedIds.clear();afterChange();showToast('Página duplicada')}
async function loadProject(id){const loaded=await getProject(id);if(!loaded)return;project=migrateProject(loaded);histories.clear();selectedIds.clear();document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls()}
async function refreshProjectList(){const select=document.getElementById('projectSelect'),items=(await listProjects()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));select.replaceChildren(...items.map(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.name;return option}));select.value=project.id}
async function createNewProject(){const name=prompt('Nombre del proyecto','Mi manga');if(!name)return;await saveProject();project=createProject(name.trim()||'Mi manga');histories.clear();selectedIds.clear();await putProject(project);document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls();showToast('Proyecto creado')}
async function duplicateProject(){await saveProject();const copy=deepClone(project);copy.id=uid('project');copy.name=`${project.name} copia`;copy.createdAt=copy.updatedAt=new Date().toISOString();copy.pages.forEach((item,index)=>{item.id=uid('page');item.name=`Página ${String(index+1).padStart(2,'0')}`;item.elements.forEach(element=>element.id=uid(element.type))});copy.activePageId=copy.pages[0].id;project=copy;await putProject(project);document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls()}
async function deleteProject(){const projects=await listProjects();if(!confirm(`¿Eliminar “${project.name}”? Esta acción no se puede deshacer.`))return;await removeProject(project.id);const remaining=projects.filter(item=>item.id!==project.id);project=remaining[0]?migrateProject(remaining[0]):createProject();await putProject(project);histories.clear();selectedIds.clear();document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls()}
function movePage(direction){const index=project.pages.indexOf(page()),next=index+direction;if(next<0||next>=project.pages.length)return;[project.pages[index],project.pages[next]]=[project.pages[next],project.pages[index]];afterChange()}
function deletePage(){if(project.pages.length===1)return showToast('El proyecto necesita al menos una página');if(!confirm(`¿Eliminar ${page().name}?`))return;const index=project.pages.indexOf(page());project.pages.splice(index,1);project.activePageId=project.pages[Math.min(index,project.pages.length-1)].id;selectedIds.clear();afterChange()}

function canvasPoint(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*W/rect.width,y:(event.clientY-rect.top)*H/rect.height}}
canvas.addEventListener('pointerdown',event=>{const point=canvasPoint(event),primary=current(),handle=primary&&!primary.locked?handleAt(point,primary):null;const hit=handle?primary:[...page().elements].reverse().find(element=>element.visible&&hitElement(point,element));if(!hit){if(!event.shiftKey)selectedIds.clear();render();updateInspector();renderLayers();return}if(event.shiftKey){selectedIds.has(hit.id)?selectedIds.delete(hit.id):selectedIds.add(hit.id)}else if(!selectedIds.has(hit.id))selectedIds=new Set([hit.id]);const selected=[...selectedIds].map(id=>page().elements.find(element=>element.id===id)).filter(element=>element&&!element.locked);if(selected.length){const mode=handle||'move',before=JSON.stringify(page());drag={mode,start:point,before,originals:selected.map(element=>({element,x:element.x,y:element.y,scale:element.scale,rotation:element.rotation})),origin:hit,startDistance:Math.hypot(point.x-hit.x,point.y-hit.y),startAngle:Math.atan2(point.y-hit.y,point.x-hit.x)};canvas.setPointerCapture(event.pointerId)}render();updateInspector();renderLayers()});
canvas.addEventListener('pointermove',event=>{if(!drag)return;const point=canvasPoint(event),dx=point.x-drag.start.x,dy=point.y-drag.start.y;guides=[];if(drag.mode==='move'){for(const item of drag.originals){item.element.x=Math.max(0,Math.min(W,item.x+dx));item.element.y=Math.max(0,Math.min(H,item.y+dy))}const primary=drag.origin;for(const value of[W/2,...panels().flatMap(panel=>[panel.x,panel.x+panel.w/2,panel.x+panel.w])])if(Math.abs(primary.x-value)<6){const offset=value-primary.x;drag.originals.forEach(item=>item.element.x+=offset);guides.push({axis:'x',value});break}for(const value of[H/2,...panels().flatMap(panel=>[panel.y,panel.y+panel.h/2,panel.y+panel.h])])if(Math.abs(primary.y-value)<6){const offset=value-primary.y;drag.originals.forEach(item=>item.element.y+=offset);guides.push({axis:'y',value});break}}
  else if(drag.mode==='scale'){const distance=Math.hypot(point.x-drag.origin.x,point.y-drag.origin.y);drag.origin.scale=Math.max(.3,Math.min(1.8,drag.originals[0].scale*distance/Math.max(1,drag.startDistance)))}
  else{drag.origin.rotation=drag.originals[0].rotation+(Math.atan2(point.y-drag.origin.y,point.x-drag.origin.x)-drag.startAngle)*180/Math.PI}render();updateInspector()});
canvas.addEventListener('pointerup',()=>{if(!drag)return;drag.originals.forEach(item=>item.element.panelId=panelAt(item.element.x,item.element.y));const before=drag.before;drag=null;guides=[];record('Transformar elementos',before)});
canvas.addEventListener('wheel',event=>{const element=current();if(!element||element.locked)return;event.preventDefault();mutate('Escalar elemento',()=>element.scale=Math.max(.3,Math.min(1.8,element.scale+(event.deltaY<0?.05:-.05))))},{passive:false});

function bindControls(){
  document.querySelectorAll('.asset-tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.asset-tab,.asset-content').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.tab).classList.add('active')});
  document.querySelectorAll('[data-add]').forEach(button=>button.onclick=()=>addElement(button.dataset.add));document.querySelectorAll('[data-bg]').forEach(button=>button.onclick=()=>mutate('Cambiar fondo',()=>page().background=button.dataset.bg));
  document.getElementById('characterCard').onclick=document.getElementById('addCharacter').onclick=()=>addElement('character');document.getElementById('backgroundSelect').onchange=event=>mutate('Cambiar fondo',()=>page().background=event.target.value);
  document.querySelectorAll('.layout-option').forEach(button=>button.onclick=()=>mutate('Cambiar viñetas',()=>page().layout=button.dataset.layout));
  document.querySelectorAll('#poseControl button').forEach(button=>button.onclick=()=>{const element=current();if(element)mutate('Cambiar pose',()=>element.pose=button.dataset.pose)});document.getElementById('expressionSelect').onchange=event=>{const element=current();if(element)mutate('Cambiar expresión',()=>element.expression=event.target.value)};
  const continuous=['scaleRange','rotateRange','textInput','fontSize'];continuous.forEach(id=>{const input=document.getElementById(id);input.onfocus=input.onpointerdown=()=>controlBefore=JSON.stringify(page());input.onchange=()=>{if(controlBefore){record('Editar propiedad',controlBefore);controlBefore=null}}});
  document.getElementById('scaleRange').oninput=event=>{const element=current();if(element&&!element.locked){element.scale=event.target.value/100;render();scheduleSave()}};document.getElementById('rotateRange').oninput=event=>{const element=current();if(element&&!element.locked){element.rotation=+event.target.value;render();scheduleSave()}};
  document.getElementById('textInput').oninput=event=>{const element=current();if(element&&!element.locked){element.text=event.target.value;render();scheduleSave()}};document.getElementById('fontSize').oninput=event=>{const element=current();if(element&&!element.locked){element.fontSize=+event.target.value;document.getElementById('fontSizeOut').value=event.target.value;render();scheduleSave()}};
  document.getElementById('flipBtn').onclick=()=>{const element=current();if(element&&!element.locked)mutate('Voltear elemento',()=>element.flip=!element.flip)};document.getElementById('deleteBtn').onclick=removeSelected;
  document.getElementById('undoBtn').onclick=()=>replacePage(history().undo(page()));document.getElementById('redoBtn').onclick=()=>replacePage(history().redo(page()));document.getElementById('newBtn').onclick=addPage;document.getElementById('duplicatePage').onclick=duplicatePage;document.getElementById('movePageLeft').onclick=()=>movePage(-1);document.getElementById('movePageRight').onclick=()=>movePage(1);document.getElementById('deletePage').onclick=deletePage;
  document.getElementById('alignHorizontal').onclick=()=>mutate('Alinear horizontal',()=>{const items=[...selectedIds].map(id=>page().elements.find(e=>e.id===id)).filter(e=>e&&!e.locked);const x=items.reduce((sum,e)=>sum+e.x,0)/items.length;items.forEach(e=>e.x=x)});document.getElementById('alignVertical').onclick=()=>mutate('Alinear vertical',()=>{const items=[...selectedIds].map(id=>page().elements.find(e=>e.id===id)).filter(e=>e&&!e.locked);const y=items.reduce((sum,e)=>sum+e.y,0)/items.length;items.forEach(e=>e.y=y)});
  document.getElementById('bringForward').onclick=()=>mutate('Subir capa',()=>{const element=current(),index=page().elements.indexOf(element);if(index>=0&&index<page().elements.length-1)[page().elements[index],page().elements[index+1]]=[page().elements[index+1],page().elements[index]]});document.getElementById('sendBackward').onclick=()=>mutate('Bajar capa',()=>{const element=current(),index=page().elements.indexOf(element);if(index>0)[page().elements[index],page().elements[index-1]]=[page().elements[index-1],page().elements[index]]});
  document.getElementById('groupLayers').onclick=()=>{if(selectedIds.size<2)return showToast('Selecciona dos o más capas con Shift');mutate('Agrupar capas',()=>{const group=uid('group');for(const element of page().elements)if(selectedIds.has(element.id))element.groupId=group})};
  document.getElementById('projectSelect').onchange=event=>loadProject(event.target.value);document.getElementById('newProject').onclick=createNewProject;document.getElementById('duplicateProject').onclick=duplicateProject;document.getElementById('deleteProject').onclick=deleteProject;document.getElementById('projectName').onchange=event=>{project.name=event.target.value.trim()||'Mi manga';scheduleSave();refreshProjectList()};
}

const poseModal=document.getElementById('poseModal');function closePoseModal(){poseModal.hidden=true;document.body.style.overflow='';window.dispatchEvent(new CustomEvent('pose3d:close'))}
document.getElementById('openPose3d').onclick=()=>{if(!current()||current().type!=='character')return;poseModal.hidden=false;document.body.style.overflow='hidden';window.dispatchEvent(new CustomEvent('pose3d:open'))};document.getElementById('closePose3d').onclick=closePoseModal;poseModal.addEventListener('click',event=>{if(event.target===poseModal)closePoseModal()});
window.addEventListener('pose3d:apply',event=>{let element=current();if(!element||element.type!=='character'){addElement('character');element=current()}mutate('Aplicar pose 3D',()=>{element.sprite=event.detail.image;element.pose=event.detail.name||'neutral';element.poseSchemaVersion=event.detail.poseSchemaVersion;element.expression='neutral';element.w=300;element.h=460;spriteCache.delete(element.id)});showToast('Pose 3D aplicada')});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!poseModal.hidden)return closePoseModal();if(drag){replacePage(JSON.parse(drag.before));drag=null;guides=[];showToast('Transformación cancelada')}return}if((event.key==='Delete'||event.key==='Backspace')&&!['TEXTAREA','INPUT'].includes(document.activeElement.tagName))removeSelected();if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?document.getElementById('redoBtn').click():document.getElementById('undoBtn').click()}});
function setZoom(value){zoom=Math.max(.48,Math.min(1.05,value));canvas.style.width=`${600*zoom}px`;canvas.style.height=`${800*zoom}px`;document.getElementById('zoomLabel').textContent=`${Math.round(zoom*100)}%`}
document.getElementById('zoomIn').onclick=()=>setZoom(zoom+.08);document.getElementById('zoomOut').onclick=()=>setZoom(zoom-.08);document.getElementById('fitBtn').onclick=()=>setZoom(innerWidth<520?.54:.82);document.getElementById('exportBtn').onclick=()=>{render(false);const link=document.createElement('a'),index=project.pages.indexOf(page())+1;link.download=`${project.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${String(index).padStart(2,'0')}.png`;link.href=canvas.toDataURL('image/png');link.click();render();showToast('PNG descargado')};

async function init(){bindControls();let projects=[];try{projects=await listProjects()}catch(error){console.error(error);showToast('IndexedDB no está disponible')};const activeId=localStorage.getItem('manga-studio-active-project');project=migrateProject(projects.find(item=>item.id===activeId)||projects[0]||(()=>{try{return JSON.parse(localStorage.getItem('manga-studio-state'))}catch{return null}})());await putProject(project);document.getElementById('projectName').value=project.name;await refreshProjectList();setZoom(innerWidth<520?.54:.82);syncPageControls();characterImage.onload=render;window.addEventListener('resize',()=>{if(innerWidth<520&&zoom>.6)setZoom(.54)});setSaveState(projects.length?'Proyecto recuperado ✓':'Proyecto creado ✓')}
init();
