import{CommandHistory,DOCUMENT_SCHEMA_VERSION,createPage,createProject,deepClone,migrateProject,uid}from'./document-model.js';
import{getProject,listProjects,putProject,removeProject}from'./project-store.js';
import{svgLooksSafe,validateAssetFile}from'./asset-validation.js';
import{mimeForFormat,resolveExportSize,safeFilename}from'./export-profiles.js';
import{MAX_PORTABLE_BYTES,createPortableProject,readPortableProject,zipEncode}from'./portable-format.js';
import{createJpegPdf}from'./pdf-export.js';
import{applyDpiMetadata}from'./image-metadata.js';

const canvas=document.getElementById('mangaCanvas'),W=canvas.width,H=canvas.height;let ctx=canvas.getContext('2d');const mainContext=ctx;
const characterImage=new Image();characterImage.src='akira.png';const spriteCache=new Map(),assetImageCache=new Map();
let project,zoom=.82,selectedIds=new Set(),drag=null,toastTimer,saveTimer,controlBefore=null,guides=[];
const histories=new Map();
const page=()=>project.pages.find(item=>item.id===project.activePageId)||project.pages[0];
const history=()=>{if(!histories.has(page().id))histories.set(page().id,new CommandHistory());return histories.get(page().id)};
const current=()=>[...selectedIds].map(id=>page().elements.find(element=>element.id===id)).filter(Boolean).at(-1);

function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
function setSaveState(message){document.getElementById('saveState').textContent=message}
function panels(){const layout=page().layout;let result;if(layout==='one')result=[{x:25,y:25,w:550,h:750}];else if(layout==='two')result=[{x:25,y:25,w:550,h:360},{x:25,y:405,w:550,h:370}];else if(layout==='four')result=[{x:25,y:25,w:265,h:365},{x:310,y:25,w:265,h:365},{x:25,y:410,w:265,h:365},{x:310,y:410,w:265,h:365}];else result=[{x:25,y:25,w:550,h:315},{x:25,y:360,w:260,h:415},{x:305,y:360,w:270,h:415}];const settings=page().panelSettings||{},delta=((settings.gutter||20)-20)/2;return result.map(panel=>({x:panel.x+delta,y:panel.y+delta,w:panel.w-delta*2,h:panel.h-delta*2}))}

function tracePanel(panel,padding=0){const slant=(page().panelSettings?.slant||0)*.65,x=panel.x,y=panel.y,w=panel.w,h=panel.h;ctx.beginPath();ctx.moveTo(x+padding+Math.max(slant,0),y+padding);ctx.lineTo(x+w-padding+Math.min(slant,0),y+padding);ctx.lineTo(x+w-padding-Math.max(slant,0),y+h-padding);ctx.lineTo(x+padding-Math.min(slant,0),y+h-padding);ctx.closePath()}

function assetImage(asset){if(!asset)return null;if(!assetImageCache.has(asset.id)){const image=new Image();image.onload=render;image.src=asset.dataUrl;assetImageCache.set(asset.id,image)}return assetImageCache.get(asset.id)}
function drawCover(image,panel,transform={}){if(!image?.complete||!image.naturalWidth)return;const scale=Math.max(panel.w/image.naturalWidth,panel.h/image.naturalHeight)*(transform.scale||100)/100,w=image.naturalWidth*scale,h=image.naturalHeight*scale,x=panel.x+(panel.w-w)/2+(transform.x||0)/100*panel.w,y=panel.y+(panel.h-h)/2+(transform.y||0)/100*panel.h;ctx.drawImage(image,x,y,w,h)}

function drawBackground(panel,index){ctx.save();tracePanel(panel);ctx.clip();const bg=page().background;
  const bgAsset=project.assets?.find(asset=>asset.id===page().backgroundAssetId);if(bgAsset){ctx.filter=`${page().backgroundMonochrome?'grayscale(1) contrast(1.08)':''} blur(${page().backgroundBlur||0}px)`.trim()||'none';ctx.globalAlpha=page().backgroundOpacity??1;drawCover(assetImage(bgAsset),panel,page().backgroundTransform);ctx.globalAlpha=1;ctx.filter='none';ctx.restore();ctx.save();tracePanel(panel);ctx.strokeStyle='#111';ctx.lineWidth=page().panelSettings?.border||6;ctx.stroke();ctx.restore();return}
  if(bg==='city'){const gradient=ctx.createLinearGradient(0,panel.y,0,panel.y+panel.h);gradient.addColorStop(0,index?'#d6d3ca':'#40434b');gradient.addColorStop(1,index?'#8b8d91':'#9b8760');ctx.fillStyle=gradient;ctx.fillRect(panel.x,panel.y,panel.w,panel.h);ctx.fillStyle='#202126';for(let x=panel.x-10;x<panel.x+panel.w;x+=48){const height=70+(x*13%130);ctx.fillRect(x,panel.y+panel.h-height,38,height);ctx.fillStyle='#e1b64a';for(let y=panel.y+panel.h-height+14;y<panel.y+panel.h-12;y+=22){ctx.fillRect(x+7,y,7,6);ctx.fillRect(x+22,y,7,6)}ctx.fillStyle='#202126'}}
  else if(bg==='dots'){const tone=page().toneSettings,step=Math.max(3,(tone.density||8)*(tone.scale||100)/100),radius=Math.max(1,step*.21);ctx.fillStyle='#eee';ctx.fillRect(panel.x,panel.y,panel.w,panel.h);ctx.translate(panel.x+panel.w/2,panel.y+panel.h/2);ctx.rotate((tone.angle||0)*Math.PI/180);ctx.translate(-panel.x-panel.w/2,-panel.y-panel.h/2);ctx.fillStyle='#777';for(let y=panel.y-panel.h;y<panel.y+panel.h*2;y+=step)for(let x=panel.x-panel.w+(Math.round(y/step)%2?step/2:0);x<panel.x+panel.w*2;x+=step){ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fill()}}
  else if(bg==='speed'){const tone=page().toneSettings,spacing=Math.max(12,37*(tone.scale||100)/100),slope=80+(tone.angle||0)*2;ctx.fillStyle='#efeee9';ctx.fillRect(panel.x,panel.y,panel.w,panel.h);ctx.strokeStyle='#555';ctx.lineWidth=Math.max(.6,10/(tone.density||8));for(let i=0;i<Math.ceil(panel.h/spacing)+8;i++){ctx.beginPath();ctx.moveTo(panel.x-40,panel.y+(i*spacing)%panel.h);ctx.lineTo(panel.x+panel.w+40,panel.y+(i*spacing)%panel.h-slope);ctx.stroke()}}
  else if(bg==='burst'){const tone=page().toneSettings,rays=Math.max(18,Math.round(288/(tone.density||8)));ctx.fillStyle='#eee';ctx.fillRect(panel.x,panel.y,panel.w,panel.h);ctx.translate(panel.x+panel.w/2,panel.y+panel.h/2);ctx.rotate((tone.angle||0)*Math.PI/180);for(let i=0;i<rays;i++){ctx.rotate(Math.PI*2/rays);ctx.beginPath();ctx.moveTo(35,-2);ctx.lineTo(Math.max(panel.w,panel.h),-7);ctx.lineTo(Math.max(panel.w,panel.h),7);ctx.closePath();ctx.fillStyle=i%3===0?'#777':'#d3d1ca';ctx.fill()}}
  else{ctx.fillStyle='#faf9f4';ctx.fillRect(panel.x,panel.y,panel.w,panel.h)}ctx.restore();ctx.save();tracePanel(panel);ctx.strokeStyle='#111';ctx.lineWidth=page().panelSettings?.border||6;ctx.stroke();ctx.restore()}

function imageFor(element){if(!element.sprite)return characterImage;if(!spriteCache.has(element.id)){const image=new Image();image.onload=render;image.src=element.sprite;spriteCache.set(element.id,image)}return spriteCache.get(element.id)}
function wrapText(text,maxWidth,font){ctx.font=font;const lines=[];for(const paragraph of String(text||'').split('\n')){const tokens=globalThis.Intl?.Segmenter?[...new Intl.Segmenter(undefined,{granularity:'word'}).segment(paragraph)].map(part=>part.segment):paragraph.split(/(\s+)/);let line='';for(const token of tokens){if(ctx.measureText(line+token).width<=maxWidth){line+=token;continue}if(line.trim())lines.push(line.trimEnd());line='';for(const char of [...token]){if(line&&ctx.measureText(line+char).width>maxWidth){lines.push(line);line=char}else line+=char}line=line.trimStart()}lines.push(line)}return lines}
function drawCharacter(element){ctx.save();ctx.translate(element.x,element.y);ctx.rotate(element.rotation*Math.PI/180);ctx.scale((element.flip?-1:1)*element.scale,element.scale);if(element.expression==='angry')ctx.filter='contrast(1.22) saturate(.8)';if(element.expression==='happy')ctx.filter='saturate(1.25) brightness(1.06)';if(element.expression==='surprised')ctx.filter='brightness(1.13) contrast(1.08)';const image=imageFor(element);if(image.complete)ctx.drawImage(image,-element.w/2,-element.h/2,element.w,element.h);ctx.restore()}
function drawImageElement(element){ctx.save();ctx.translate(element.x,element.y);ctx.rotate(element.rotation*Math.PI/180);ctx.scale((element.flip?-1:1)*element.scale,element.scale);const image=assetImage(project.assets?.find(asset=>asset.id===element.assetId));if(image?.complete)ctx.drawImage(image,-element.w/2,-element.h/2,element.w,element.h);ctx.restore()}
function drawTextElement(element){ctx.save();ctx.translate(element.x,element.y);ctx.rotate(element.rotation*Math.PI/180);ctx.scale((element.flip?-1:1)*element.scale,element.scale);const{w,h}=element;
  if(element.type==='bubble'||element.type==='thought'){ctx.fillStyle='#fff';ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(element.type==='thought'){ctx.beginPath();ctx.arc((element.tailSide==='left'?-1:1)*w*.2,h*.52,10,0,Math.PI*2);ctx.arc((element.tailSide==='left'?-1:1)*w*.27,h*.68,5,0,Math.PI*2);ctx.fill();ctx.stroke()}else if(element.tailSide!=='none'){const side=element.tailSide==='left'?-1:1;ctx.beginPath();ctx.moveTo(side*w*.2,h*.38);ctx.lineTo(side*w*.36,h*.72);ctx.lineTo(side*w*.04,h*.45);ctx.fill();ctx.stroke()}}
  if(element.type==='shout'){ctx.fillStyle='#fff';ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<24;i++){const angle=i*Math.PI/12,radius=i%2?Math.min(w,h)*.37:Math.min(w,h)*.55;const x=Math.cos(angle)*radius,y=Math.sin(angle)*radius;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke()}
  if(element.type==='caption'){ctx.fillStyle='#111';ctx.fillRect(-w/2,-h/2,w,h)}const fx=element.type==='fx';ctx.fillStyle=element.type==='caption'?'#fff':fx?'#f3b61f':'#111';ctx.strokeStyle=fx?'#111':'transparent';ctx.lineWidth=fx?7:0;ctx.textAlign=element.textAlign||'center';ctx.textBaseline='middle';ctx.letterSpacing=`${element.letterSpacing||0}px`;const size=element.fontSize||24,family=element.fontFamily||'Arial';ctx.font=`${fx?'900 italic':'800'} ${size}px ${family}`;const padding=element.bubblePadding||12,lines=wrapText(element.text,w-padding*2,ctx.font);lines.forEach((line,index)=>{const y=(index-(lines.length-1)/2)*size*(element.lineHeight||1.08);const x=ctx.textAlign==='left'?-w/2+padding:ctx.textAlign==='right'?w/2-padding:0;if(fx)ctx.strokeText(line,x,y);ctx.fillText(line,x,y)});ctx.restore()}
function drawElement(element){const panel=Number.isInteger(element.panelId)?panels()[element.panelId]:null;ctx.save();if(panel){tracePanel(panel,3);ctx.clip()}element.type==='character'?drawCharacter(element):element.type==='image'?drawImageElement(element):drawTextElement(element);ctx.restore()}
function localPoint(point,element){const angle=-element.rotation*Math.PI/180,dx=point.x-element.x,dy=point.y-element.y;return{x:(dx*Math.cos(angle)-dy*Math.sin(angle))/element.scale,y:(dx*Math.sin(angle)+dy*Math.cos(angle))/element.scale}}
function hitElement(point,element){const local=localPoint(point,element);return Math.abs(local.x)<=element.w/2&&Math.abs(local.y)<=element.h/2}
function handleAt(point,element){const local=localPoint(point,element),corners=[[-element.w/2,-element.h/2],[element.w/2,-element.h/2],[-element.w/2,element.h/2],[element.w/2,element.h/2]];if(Math.hypot(local.x,local.y+element.h/2+28)<13)return'rotate';return corners.some(([x,y])=>Math.hypot(local.x-x,local.y-y)<12)?'scale':null}
function drawSelection(element,primary){ctx.save();ctx.translate(element.x,element.y);ctx.rotate(element.rotation*Math.PI/180);ctx.scale(element.scale,element.scale);ctx.strokeStyle=element.locked?'#ef6b57':'#f3b61f';ctx.lineWidth=2/element.scale;ctx.setLineDash([7/element.scale,5/element.scale]);ctx.strokeRect(-element.w/2,-element.h/2,element.w,element.h);ctx.setLineDash([]);if(primary){ctx.fillStyle='#f3b61f';for(const[x,y]of[[-element.w/2,-element.h/2],[element.w/2,-element.h/2],[-element.w/2,element.h/2],[element.w/2,element.h/2]])ctx.fillRect(x-5/element.scale,y-5/element.scale,10/element.scale,10/element.scale);ctx.beginPath();ctx.arc(0,-element.h/2-28,6/element.scale,0,Math.PI*2);ctx.fill()}ctx.restore()}
function render(withSelection=true){ctx.clearRect(0,0,W,H);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);panels().forEach(drawBackground);page().elements.filter(element=>element.visible!==false).forEach(drawElement);if(withSelection)[...selectedIds].forEach((id,index,array)=>{const element=page().elements.find(item=>item.id===id);if(element?.visible)drawSelection(element,index===array.length-1)});if(guides.length){ctx.save();ctx.strokeStyle='#55d6be';ctx.lineWidth=1;ctx.setLineDash([4,4]);for(const guide of guides){ctx.beginPath();guide.axis==='x'?(ctx.moveTo(guide.value,0),ctx.lineTo(guide.value,H)):(ctx.moveTo(0,guide.value),ctx.lineTo(W,guide.value));ctx.stroke()}ctx.restore()}if(withSelection&&page().panelSettings?.bleed){ctx.save();ctx.strokeStyle='#e65b50';ctx.lineWidth=2;ctx.setLineDash([9,6]);ctx.strokeRect(8,8,W-16,H-16);ctx.fillStyle='#e65b50';ctx.font='700 10px Arial';ctx.textAlign='left';ctx.fillText('LÍMITE DE SANGRADO',14,22);ctx.restore()}}

function record(label,before){const after=JSON.stringify(page());history().push({label,before,after});afterChange()}
function mutate(label,operation){const before=JSON.stringify(page());operation();record(label,before)}
function replacePage(next){const index=project.pages.findIndex(item=>item.id===project.activePageId);project.pages[index]=next;project.activePageId=next.id;selectedIds.clear();afterChange()}
function afterChange(){project.updatedAt=new Date().toISOString();render();updateInspector();renderLayers();renderPageRail();renderAssetLibrary();scheduleSave()}
function scheduleSave(){setSaveState('Guardando…');clearTimeout(saveTimer);saveTimer=setTimeout(saveProject,350)}
async function saveProject(){try{render(false);page().thumbnail=canvas.toDataURL('image/jpeg',.55);render();await putProject(project);localStorage.setItem('manga-studio-active-project',project.id);setSaveState('Guardado ✓')}catch(error){console.error(error);setSaveState('Error al guardar');showToast('No se pudo guardar el proyecto')}}

function addElement(type){mutate('Añadir elemento',()=>{const id=uid(type);let element;if(type==='character')element={id,type,name:'Akira',x:300,y:420,w:260,h:410,scale:.82,rotation:0,flip:false,pose:'neutral',expression:'neutral'};else{const meta={bubble:['Diálogo','¿Qué está pasando?',230,110,23],shout:['Grito','¡DETENTE!',220,150,29],thought:['Pensamiento','Tengo un mal presentimiento…',235,125,21],caption:['Narración','MIENTRAS TANTO…',250,62,19],fx:['Efecto','¡BAM!',210,100,46]}[type];element={id,type,name:meta[0],text:meta[1],x:300,y:210,w:meta[2],h:meta[3],fontSize:meta[4],fontFamily:'Arial',textAlign:'center',lineHeight:1.08,letterSpacing:0,bubblePadding:12,tailSide:'right',scale:1,rotation:0,flip:false}}Object.assign(element,{visible:true,locked:false,panelId:panelAt(element.x,element.y)});page().elements.push(element);selectedIds=new Set([id])});showToast(type==='character'?'Personaje añadido':'Elemento añadido')}
function addAssetElement(asset){mutate('Añadir recurso',()=>{const element={id:uid('image'),type:'image',name:asset.name,assetId:asset.id,x:300,y:400,w:300,h:300,scale:1,rotation:0,flip:false,visible:true,locked:false,panelId:1};page().elements.push(element);selectedIds=new Set([element.id]);asset.lastUsedAt=new Date().toISOString()});showToast('Recurso añadido a la página')}
function panelAt(x,y){return panels().findIndex(panel=>x>=panel.x&&x<=panel.x+panel.w&&y>=panel.y&&y<=panel.y+panel.h)}
function removeSelected(){if(!selectedIds.size)return;mutate('Eliminar elementos',()=>page().elements=page().elements.filter(element=>!selectedIds.has(element.id)));selectedIds.clear();afterChange();showToast('Elemento eliminado')}

function updateInspector(){const element=current(),count=selectedIds.size,isText=element&&!['character','image'].includes(element.type);document.getElementById('selectionName').textContent=count>1?`${count} elementos`:element?.name||'Página';document.getElementById('characterControls').hidden=!element||element.type!=='character'||count>1;document.getElementById('textControls').hidden=!isText||count>1;document.getElementById('transformControls').hidden=!element;if(!element)return;document.getElementById('scaleRange').value=Math.round(element.scale*100);document.getElementById('rotateRange').value=element.rotation||0;if(element.type==='character'){document.getElementById('expressionSelect').value=element.expression;document.querySelectorAll('#poseControl button').forEach(button=>button.classList.toggle('active',button.dataset.pose===element.pose))}else if(isText){document.getElementById('textInput').value=element.text;document.getElementById('fontSize').value=element.fontSize;document.getElementById('fontSizeOut').value=element.fontSize;document.getElementById('fontFamily').value=element.fontFamily||'Arial';document.getElementById('textAlign').value=element.textAlign||'center';document.getElementById('lineHeight').value=element.lineHeight||1.08;document.getElementById('letterSpacing').value=element.letterSpacing||0;document.getElementById('letterSpacingOut').value=element.letterSpacing||0;document.getElementById('tailSide').value=element.tailSide||'right';document.getElementById('bubblePadding').value=element.bubblePadding||12;document.getElementById('bubbleControls').hidden=!['bubble','thought'].includes(element.type)}}

function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
function decodeImage(dataUrl){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve();image.onerror=()=>reject(new Error('No se pudo decodificar la imagen'));image.src=dataUrl})}
async function importImages(files){let imported=0;for(const file of files){const validation=validateAssetFile(file);if(!validation.ok){showToast(validation.error);continue}if(file.type==='image/svg+xml'&&!svgLooksSafe(await file.text())){showToast(`${file.name}: SVG inseguro rechazado`);continue}const dataUrl=await fileToDataUrl(file);try{await decodeImage(dataUrl)}catch{showToast(`${file.name}: imagen dañada o ilegible`);continue}const asset={id:uid('asset'),kind:'image',name:file.name,tags:['importado'],mime:file.type,size:file.size,dataUrl,createdAt:new Date().toISOString(),lastUsedAt:null};project.assets.push(asset);imported++}if(imported)afterChange();showToast(imported?`${imported} recurso${imported===1?'':'s'} importado${imported===1?'':'s'}`:'No se importaron recursos')}
async function importVrm(file){const validation=validateAssetFile(file,'vrm');if(!validation.ok)return showToast(validation.error);if(!document.getElementById('vrmConsent').checked)return showToast('Confirma que puedes usar este avatar');const header=new DataView(await file.slice(0,12).arrayBuffer());if(header.byteLength<12||header.getUint32(0,true)!==0x46546c67)return showToast('El archivo no contiene un contenedor VRM/GLB válido');const asset={id:uid('vrm'),kind:'vrm',name:file.name,tags:['avatar','vrm'],mime:file.type||'model/gltf-binary',size:file.size,blob:file,createdAt:new Date().toISOString()};project.assets.push(asset);project.activeVrmAssetId=asset.id;afterChange();window.dispatchEvent(new CustomEvent('pose3d:load-avatar',{detail:{blob:file,name:file.name}}));showToast('Avatar VRM preparado')}
function renderAssetLibrary(){if(!project)return;const query=(document.getElementById('assetSearch').value||'').toLowerCase(),list=document.getElementById('assetLibrary');list.innerHTML='';const assets=(project.assets||[]).filter(asset=>asset.kind==='image'&&`${asset.name} ${(asset.tags||[]).join(' ')}`.toLowerCase().includes(query)).sort((a,b)=>(b.lastUsedAt||b.createdAt).localeCompare(a.lastUsedAt||a.createdAt));document.getElementById('assetEmpty').hidden=assets.length>0;for(const asset of assets){const card=document.createElement('article');card.className='user-asset';const image=document.createElement('img');image.src=asset.dataUrl;image.alt='';const body=document.createElement('div'),name=document.createElement('b'),meta=document.createElement('small'),actions=document.createElement('div'),add=document.createElement('button'),background=document.createElement('button');name.textContent=asset.name;meta.textContent=`${Math.round(asset.size/1024)} KB · ${(asset.tags||[]).join(', ')}`;actions.className='asset-card-actions';add.textContent='Añadir';background.textContent='Fondo';add.onclick=()=>addAssetElement(asset);background.onclick=()=>mutate('Usar fondo importado',()=>{page().backgroundAssetId=asset.id;page().background='imported'});actions.append(add,background);body.append(name,meta,actions);card.append(image,body);list.append(card)}}
function selectLayer(element){const grouped=element.groupId?page().elements.filter(item=>item.groupId===element.groupId):[element];selectedIds=new Set(grouped.map(item=>item.id));render();updateInspector();renderLayers()}
function renderLayers(){const list=document.getElementById('layerList');list.innerHTML='';[...page().elements].reverse().forEach(element=>{const row=document.createElement('div');row.className='layer-row'+(selectedIds.has(element.id)?' active':'');const select=document.createElement('button'),visible=document.createElement('button'),locked=document.createElement('button');select.className='layer-select';select.textContent=(element.groupId?'◆ ':'')+element.name;select.title='Seleccionar · doble clic para renombrar';visible.className=locked.className='layer-state';visible.textContent=element.visible?'◉':'○';visible.title='Mostrar u ocultar';locked.textContent=element.locked?'🔒':'◇';locked.title='Bloquear o desbloquear';select.onclick=()=>selectLayer(element);select.ondblclick=()=>{const name=prompt('Nombre de la capa',element.name);if(name?.trim())mutate('Renombrar capa',()=>element.name=name.trim())};visible.onclick=()=>mutate('Visibilidad de capa',()=>element.visible=!element.visible);locked.onclick=()=>mutate('Bloqueo de capa',()=>element.locked=!element.locked);row.append(select,visible,locked);list.append(row)})}
function renderPageRail(){document.getElementById('pageTitle').textContent=page().name;const rail=document.getElementById('pageRail');rail.innerHTML='';project.pages.forEach((item,index)=>{const button=document.createElement('button');button.className='page-card'+(item.id===project.activePageId?' active':'');button.innerHTML=item.thumbnail?`<img src="${item.thumbnail}" alt=""><span>${index+1}</span>`:`<i></i><span>${index+1}</span>`;button.title=item.name;button.onclick=async()=>{if(item.id===project.activePageId)return;await saveProject();project.activePageId=item.id;selectedIds.clear();syncPageControls();afterChange()};rail.append(button)});const add=document.createElement('button');add.className='page-add';add.textContent='＋';add.title='Añadir página';add.onclick=addPage;rail.append(add)}
function syncPageControls(){document.querySelectorAll('.layout-option').forEach(button=>button.classList.toggle('active',button.dataset.layout===page().layout));document.getElementById('backgroundSelect').value=page().background;const panel=page().panelSettings,tone=page().toneSettings,background=page().backgroundTransform;document.getElementById('panelGutter').value=panel.gutter;document.getElementById('panelBorder').value=panel.border;document.getElementById('panelSlant').value=panel.slant;document.getElementById('pageBleed').checked=panel.bleed;document.getElementById('toneDensity').value=tone.density;document.getElementById('toneScale').value=tone.scale;document.getElementById('toneAngle').value=tone.angle;document.getElementById('backgroundOpacity').value=Math.round((page().backgroundOpacity??1)*100);document.getElementById('backgroundBlur').value=page().backgroundBlur||0;document.getElementById('backgroundScale').value=background.scale;document.getElementById('backgroundOffsetX').value=background.x;document.getElementById('backgroundOffsetY').value=background.y;document.getElementById('backgroundMonochrome').checked=!!page().backgroundMonochrome;render();updateInspector();renderLayers();renderPageRail();renderAssetLibrary()}

function addPage(){const next=createPage(project.pages.length);project.pages.push(next);project.activePageId=next.id;selectedIds.clear();afterChange();showToast('Página añadida')}
function duplicatePage(){const copy=deepClone(page());copy.id=uid('page');copy.name=`${page().name} copia`;copy.elements.forEach(element=>element.id=uid(element.type));project.pages.splice(project.pages.indexOf(page())+1,0,copy);project.activePageId=copy.id;selectedIds.clear();afterChange();showToast('Página duplicada')}
async function loadProject(id){const loaded=await getProject(id);if(!loaded)return;project=migrateProject(loaded);histories.clear();selectedIds.clear();document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls()}
async function refreshProjectList(){const select=document.getElementById('projectSelect'),items=(await listProjects()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));select.replaceChildren(...items.map(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.name;return option}));select.value=project.id}
async function createNewProject(){const name=prompt('Nombre del proyecto','Mi manga');if(!name)return;await saveProject();project=createProject(name.trim()||'Mi manga');histories.clear();selectedIds.clear();await putProject(project);document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls();showToast('Proyecto creado')}
async function duplicateProject(){await saveProject();const copy=deepClone(project);copy.id=uid('project');copy.name=`${project.name} copia`;copy.createdAt=copy.updatedAt=new Date().toISOString();copy.pages.forEach((item,index)=>{item.id=uid('page');item.name=`Página ${String(index+1).padStart(2,'0')}`;item.elements.forEach(element=>element.id=uid(element.type))});copy.activePageId=copy.pages[0].id;project=copy;await putProject(project);document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls()}
async function deleteProject(){const projects=await listProjects();if(!confirm(`¿Eliminar “${project.name}”? Esta acción no se puede deshacer.`))return;await removeProject(project.id);const remaining=projects.filter(item=>item.id!==project.id);project=remaining[0]?migrateProject(remaining[0]):createProject();await putProject(project);histories.clear();selectedIds.clear();document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls()}
function movePage(direction){const index=project.pages.indexOf(page()),next=index+direction;if(next<0||next>=project.pages.length)return;[project.pages[index],project.pages[next]]=[project.pages[next],project.pages[index]];afterChange()}
function deletePage(){if(project.pages.length===1)return showToast('El proyecto necesita al menos una página');if(!confirm(`¿Eliminar ${page().name}?`))return;const index=project.pages.indexOf(page());project.pages.splice(index,1);project.activePageId=project.pages[Math.min(index,project.pages.length-1)].id;selectedIds.clear();afterChange()}

function canvasPoint(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*W/rect.width,y:(event.clientY-rect.top)*H/rect.height}}
canvas.addEventListener('pointerdown',event=>{const point=canvasPoint(event),primary=current(),handle=primary&&!primary.locked?handleAt(point,primary):null;const hit=handle?primary:[...page().elements].reverse().find(element=>element.visible&&hitElement(point,element));if(!hit){if(!event.shiftKey)selectedIds.clear();render();updateInspector();renderLayers();return}if(event.shiftKey){selectedIds.has(hit.id)?selectedIds.delete(hit.id):selectedIds.add(hit.id)}else if(!selectedIds.has(hit.id))selectedIds=new Set([hit.id]);const selected=[...selectedIds].map(id=>page().elements.find(element=>element.id===id)).filter(element=>element&&!element.locked);if(selected.length){const mode=handle||'move',before=JSON.stringify(page());drag={mode,start:point,before,originals:selected.map(element=>({element,x:element.x,y:element.y,scale:element.scale,rotation:element.rotation})),origin:hit,startDistance:Math.hypot(point.x-hit.x,point.y-hit.y),startAngle:Math.atan2(point.y-hit.y,point.x-hit.x)};canvas.setPointerCapture(event.pointerId)}render();updateInspector();renderLayers()});
canvas.addEventListener('pointermove',event=>{if(!drag)return;const point=canvasPoint(event),dx=point.x-drag.start.x,dy=point.y-drag.start.y;guides=[];if(drag.mode==='move'){for(const item of drag.originals){item.element.x=Math.max(0,Math.min(W,item.x+dx));item.element.y=Math.max(0,Math.min(H,item.y+dy))}const primary=drag.origin;for(const value of[W/2,...panels().flatMap(panel=>[panel.x,panel.x+panel.w/2,panel.x+panel.w])])if(Math.abs(primary.x-value)<6){const offset=value-primary.x;drag.originals.forEach(item=>item.element.x+=offset);guides.push({axis:'x',value});break}for(const value of[H/2,...panels().flatMap(panel=>[panel.y,panel.y+panel.h/2,panel.y+panel.h])])if(Math.abs(primary.y-value)<6){const offset=value-primary.y;drag.originals.forEach(item=>item.element.y+=offset);guides.push({axis:'y',value});break}}
  else if(drag.mode==='scale'){const distance=Math.hypot(point.x-drag.origin.x,point.y-drag.origin.y);drag.origin.scale=Math.max(.3,Math.min(1.8,drag.originals[0].scale*distance/Math.max(1,drag.startDistance)))}
  else{drag.origin.rotation=drag.originals[0].rotation+(Math.atan2(point.y-drag.origin.y,point.x-drag.origin.x)-drag.startAngle)*180/Math.PI}render();updateInspector()});
canvas.addEventListener('pointerup',()=>{if(!drag)return;drag.originals.forEach(item=>item.element.panelId=panelAt(item.element.x,item.element.y));const before=drag.before;drag=null;guides=[];record('Transformar elementos',before)});
canvas.addEventListener('wheel',event=>{const element=current();if(!element||element.locked)return;event.preventDefault();mutate('Escalar elemento',()=>element.scale=Math.max(.3,Math.min(1.8,element.scale+(event.deltaY<0?.05:-.05))))},{passive:false});

function editTextInline(element){if(!element||['character','image'].includes(element.type)||element.locked)return;const before=JSON.stringify(page()),rect=canvas.getBoundingClientRect(),scaleX=rect.width/W,scaleY=rect.height/H,editor=document.createElement('textarea');editor.className='inline-text-editor';editor.value=element.text||'';editor.style.left=`${rect.left+(element.x-element.w*element.scale/2)*scaleX}px`;editor.style.top=`${rect.top+(element.y-element.h*element.scale/2)*scaleY}px`;editor.style.width=`${Math.max(120,element.w*element.scale*scaleX)}px`;editor.style.height=`${Math.max(70,element.h*element.scale*scaleY)}px`;editor.style.font=`${element.fontSize*element.scale*scaleY}px ${element.fontFamily||'Arial'}`;editor.style.transform=`rotate(${element.rotation}deg)`;document.body.append(editor);editor.focus();editor.select();let finished=false;const finish=cancel=>{if(finished)return;finished=true;editor.remove();if(cancel)replacePage(JSON.parse(before));else record('Editar texto en lienzo',before)};editor.oninput=()=>{element.text=editor.value;render()};editor.onblur=()=>finish(false);editor.onkeydown=event=>{event.stopPropagation();if(event.key==='Escape'){event.preventDefault();finish(true)}if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();finish(false)}}}
canvas.addEventListener('dblclick',event=>{const point=canvasPoint(event),element=[...page().elements].reverse().find(item=>item.visible&&hitElement(point,item));editTextInline(element)});

function cyclePanels(direction){const order=['one','two','cinematic','four'],index=order.indexOf(page().layout),next=Math.max(0,Math.min(order.length-1,index+direction));mutate(direction>0?'Dividir viñetas':'Unir viñetas',()=>{page().layout=order[next];page().elements.forEach(element=>element.panelId=Math.min(Math.max(0,element.panelId||0),panels().length-1))})}
function applyTemplate(name){const templates={dialogue:{layout:'two',background:'city',tone:{density:8,scale:100,angle:0}},action:{layout:'cinematic',background:'speed',tone:{density:10,scale:75,angle:-12}},yonkoma:{layout:'four',background:'blank',tone:{density:8,scale:100,angle:0}}},template=templates[name];mutate('Aplicar plantilla',()=>{page().layout=template.layout;page().background=template.background;page().backgroundAssetId=null;page().toneSettings={...template.tone}});showToast('Plantilla aplicada sin borrar tus capas')}
function bindPageRange(id,object,key,transform=value=>+value){const input=document.getElementById(id);input.onpointerdown=input.onfocus=()=>controlBefore=JSON.stringify(page());input.oninput=event=>{object()[key]=transform(event.target.value);render()};input.onchange=()=>{if(controlBefore){record('Ajustar página',controlBefore);controlBefore=null}}}

function createSurface(width,height){if(typeof OffscreenCanvas!=='undefined')return new OffscreenCanvas(width,height);const surface=document.createElement('canvas');surface.width=width;surface.height=height;return surface}
function surfaceToBlob(surface,type,quality){if(surface.convertToBlob)return surface.convertToBlob({type,quality});return new Promise((resolve,reject)=>surface.toBlob(blob=>blob?resolve(blob):reject(new Error(`El navegador no pudo generar ${type}`)),type,quality))}
async function encodedSurfaceBlob(surface,type,quality,dpi){const raw=await surfaceToBlob(surface,type,quality);if(!raw.type.includes(type.split('/')[1]))throw new Error(`Este navegador no admite ${type.split('/')[1].toUpperCase()}`);return new Blob([applyDpiMetadata(new Uint8Array(await raw.arrayBuffer()),type,dpi)],{type})}
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function waitForImage(image,label){if(image.complete)return image.naturalWidth?Promise.resolve():Promise.reject(new Error(`${label} no se puede decodificar`));return new Promise((resolve,reject)=>{image.addEventListener('load',resolve,{once:true});image.addEventListener('error',()=>reject(new Error(`${label} no se puede decodificar`)),{once:true})})}
async function preloadPageAssets(targetPage){const images=new Map();for(const element of targetPage.elements){if(element.type==='character')images.set(element.id,{image:imageFor(element),label:element.name});if(element.type==='image'){const asset=project.assets?.find(item=>item.id===element.assetId);if(asset)images.set(asset.id,{image:assetImage(asset),label:asset.name})}}const background=project.assets?.find(item=>item.id===targetPage.backgroundAssetId);if(background)images.set(background.id,{image:assetImage(background),label:background.name});await Promise.all([...images.values()].map(item=>waitForImage(item.image,item.label)))}
function exportConfig(){const profile=document.getElementById('exportProfile').value,scale=+document.getElementById('exportScale').value,size=resolveExportSize({profile,scale,width:+document.getElementById('exportWidth').value,height:+document.getElementById('exportHeight').value,dpi:+document.getElementById('exportDpi').value});return{profile,size,format:document.getElementById('exportFormat').value,scope:document.getElementById('exportScope').value,quality:+document.getElementById('exportQuality').value/100,bleed:document.getElementById('exportBleed').checked,marks:document.getElementById('exportMarks').checked}}
function exportPages(config){const pages=config.scope==='all'?project.pages:[page()];if(config.size.width*config.size.height*pages.length>240_000_000)throw new RangeError('El lote supera el presupuesto seguro de 240 megapíxeles; usa un perfil menor o exporta por partes');return pages}
function collectExportWarnings(pages,size){const warnings=new Set(),pixelScale=Math.min(size.width/W,size.height/H);for(const targetPage of pages){const background=project.assets?.find(item=>item.id===targetPage.backgroundAssetId),backgroundImage=background&&assetImage(background);if(backgroundImage?.naturalWidth&&backgroundImage.naturalWidth<size.width)warnings.add(`${background.name}: resolución baja como fondo para este perfil`);for(const element of targetPage.elements){const halfW=element.w*element.scale/2,halfH=element.h*element.scale/2;if(element.x-halfW<0||element.y-halfH<0||element.x+halfW>W||element.y+halfH>H)warnings.add(`${targetPage.name}: hay elementos fuera de la página`);if(element.type==='image'||element.type==='character'){const asset=element.type==='image'?project.assets?.find(item=>item.id===element.assetId):null,image=element.type==='image'&&asset?assetImage(asset):imageFor(element),label=asset?.name||element.name;if(image?.naturalWidth&&image.naturalWidth<element.w*element.scale*pixelScale)warnings.add(`${label}: resolución baja para este perfil`)}if(!['character','image'].includes(element.type)&&document.fonts&&!document.fonts.check(`16px ${element.fontFamily||'Arial'}`))warnings.add(`${targetPage.name}: la fuente ${element.fontFamily} no está disponible`)}}return[...warnings]}
function drawCropMarks(context,margin,width,height){const left=margin,top=margin,right=margin+width,bottom=margin+height,length=Math.max(8,Math.min(22,margin-3));context.save();context.strokeStyle='#111';context.lineWidth=1;for(const[x,direction]of[[left,-1],[right,1]])for(const y of[top,bottom]){context.beginPath();context.moveTo(x+direction*3,y);context.lineTo(x+direction*length,y);context.stroke()}for(const[y,direction]of[[top,-1],[bottom,1]])for(const x of[left,right]){context.beginPath();context.moveTo(x,y+direction*3);context.lineTo(x,y+direction*length);context.stroke()}context.restore()}
function drawBleedExtension(context,content,margin,width,height){context.drawImage(content,0,0,width,1,margin,0,width,margin);context.drawImage(content,0,height-1,width,1,margin,margin+height,width,margin);context.drawImage(content,0,0,1,height,0,margin,margin,height);context.drawImage(content,width-1,0,1,height,margin+width,margin,margin,height);context.drawImage(content,0,0,1,1,0,0,margin,margin);context.drawImage(content,width-1,0,1,1,margin+width,0,margin,margin);context.drawImage(content,0,height-1,1,1,0,margin+height,margin,margin);context.drawImage(content,width-1,height-1,1,1,margin+width,margin+height,margin,margin)}
async function renderExportSurface(targetPage,size,{bleed=false,marks=false}={}){await preloadPageAssets(targetPage);const content=createSurface(size.width,size.height),contentContext=content.getContext('2d'),scale=Math.min(size.width/W,size.height/H),offsetX=(size.width-W*scale)/2,offsetY=(size.height-H*scale)/2,previousPageId=project.activePageId,previousContext=ctx;contentContext.fillStyle='#fff';contentContext.fillRect(0,0,size.width,size.height);try{project.activePageId=targetPage.id;ctx=contentContext;ctx.save();ctx.translate(offsetX,offsetY);ctx.scale(scale,scale);render(false);ctx.restore()}finally{ctx=previousContext;project.activePageId=previousPageId;render()}const bleedPixels=bleed?Math.round(size.dpi/25.4*3):0,margin=Math.max(bleedPixels,marks?24:0);if(!margin)return content;const output=createSurface(size.width+margin*2,size.height+margin*2),outputContext=output.getContext('2d');outputContext.fillStyle='#fff';outputContext.fillRect(0,0,output.width,output.height);if(bleed)drawBleedExtension(outputContext,content,margin,size.width,size.height);outputContext.drawImage(content,margin,margin);if(marks)drawCropMarks(outputContext,margin,size.width,size.height);return output}
function setExportProgress(message,active=true){const progress=document.getElementById('exportProgress');progress.hidden=!active;progress.querySelector('span').textContent=message}
function updateExportUi(){const custom=document.getElementById('exportProfile').value==='custom';document.getElementById('customSize').hidden=!custom;document.getElementById('exportScale').disabled=custom;document.getElementById('exportQualityOut').value=`${document.getElementById('exportQuality').value}%`;const summary=document.getElementById('exportSummary'),warnings=document.getElementById('exportWarnings');try{const config=exportConfig(),pages=exportPages(config),bleedPixels=config.bleed?Math.round(config.size.dpi/25.4*3):0,margin=Math.max(bleedPixels,config.marks?24:0);summary.textContent=`${pages.length} página${pages.length===1?'':'s'} · ${config.size.width+margin*2} × ${config.size.height+margin*2} px · ${config.size.dpi} DPI`;warnings.replaceChildren(...collectExportWarnings(pages,config.size).map(message=>{const item=document.createElement('div');item.textContent=`⚠ ${message}`;return item}))}catch(error){summary.textContent=error.message;warnings.replaceChildren()}}
async function runExport(task){const buttons=['exportImages','exportPdf','exportProjectFile'].map(id=>document.getElementById(id));buttons.forEach(button=>button.disabled=true);try{await task()}catch(error){console.error(error);document.getElementById('exportWarnings').textContent=`No se pudo exportar: ${error.message}`;showToast('La exportación no pudo completarse')}finally{buttons.forEach(button=>button.disabled=false);setExportProgress('',false)}}
async function exportImages(){const config=exportConfig(),pages=exportPages(config),mime=mimeForFormat(config.format),extension=config.format==='jpeg'?'jpg':config.format,entries={};for(let index=0;index<pages.length;index++){setExportProgress(`Renderizando página ${index+1} de ${pages.length}…`);const surface=await renderExportSurface(pages[index],config.size,config),blob=await encodedSurfaceBlob(surface,mime,config.quality,config.size.dpi);const filename=`${safeFilename(project.name)}-${String(index+1).padStart(2,'0')}.${extension}`;if(pages.length===1&&config.scope==='current')downloadBlob(blob,filename);else entries[filename]=new Uint8Array(await blob.arrayBuffer());await new Promise(resolve=>setTimeout(resolve,0))}if(Object.keys(entries).length)downloadBlob(new Blob([zipEncode(entries)],{type:'application/zip'}),`${safeFilename(project.name)}-paginas.zip`);showToast(pages.length===1?'Imagen exportada':'Lote de imágenes exportado')}
async function exportPdf(){const config=exportConfig(),pages=exportPages(config),pdfPages=[];for(let index=0;index<pages.length;index++){setExportProgress(`Preparando PDF · página ${index+1} de ${pages.length}…`);const surface=await renderExportSurface(pages[index],config.size,config),blob=await surfaceToBlob(surface,'image/jpeg',config.quality),data=new Uint8Array(await blob.arrayBuffer());if(data[0]!==0xff||data[1]!==0xd8)throw new Error('El navegador no pudo codificar JPEG para el PDF');pdfPages.push({bytes:data,width:surface.width,height:surface.height,dpi:config.size.dpi});await new Promise(resolve=>setTimeout(resolve,0))}downloadBlob(new Blob([createJpegPdf(pdfPages,{title:project.name})],{type:'application/pdf'}),`${safeFilename(project.name)}.pdf`);showToast('PDF multipágina exportado')}
async function exportProjectFile(){setExportProgress('Empaquetando proyecto y verificando recursos…');await saveProject();const packed=await createPortableProject(project,'0.6.0');if(packed.length>MAX_PORTABLE_BYTES)throw new Error('El respaldo supera el límite de 100 MB');downloadBlob(new Blob([packed],{type:'application/vnd.mangastudio+zip'}),`${safeFilename(project.name)}.mangastudio`);showToast('Respaldo portable exportado')}
async function importPortableProject(file){if(!file||!file.name.toLowerCase().endsWith('.mangastudio'))return showToast('Selecciona un archivo .mangastudio');if(file.size>MAX_PORTABLE_BYTES)return showToast('El proyecto supera el límite de 100 MB');setSaveState('Validando proyecto…');try{const{manifest,project:raw}=await readPortableProject(await file.arrayBuffer());if(manifest.documentSchemaVersion>DOCUMENT_SCHEMA_VERSION||raw.schemaVersion>DOCUMENT_SCHEMA_VERSION)throw new Error('El proyecto fue creado con una versión más nueva');for(const asset of raw.assets||[])if(asset.kind==='image')await decodeImage(asset.dataUrl);const summary=`Proyecto: ${raw.name||'Sin nombre'}\nPáginas: ${raw.pages.length}\nRecursos: ${raw.assets.length}\nVersión: ${manifest.appVersion||'desconocida'}\n\nEl archivo pasó las verificaciones de integridad. ¿Importarlo como un proyecto nuevo?`;if(!confirm(summary)){setSaveState('Importación cancelada');return}const imported=migrateProject(raw);imported.id=uid('project');imported.name=`${imported.name} (importado)`;imported.createdAt=imported.updatedAt=new Date().toISOString();project=imported;histories.clear();selectedIds.clear();await putProject(project);localStorage.setItem('manga-studio-active-project',project.id);document.getElementById('projectName').value=project.name;await refreshProjectList();syncPageControls();setSaveState('Importado y verificado ✓');showToast('Proyecto importado con integridad verificada')}catch(error){console.error(error);setSaveState('Importación rechazada');showToast(error.message)}}

function bindControls(){
  document.querySelectorAll('.asset-tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.asset-tab,.asset-content').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.tab).classList.add('active')});
  document.querySelectorAll('[data-add]').forEach(button=>button.onclick=()=>addElement(button.dataset.add));document.querySelectorAll('[data-bg]').forEach(button=>button.onclick=()=>mutate('Cambiar fondo',()=>page().background=button.dataset.bg));
  document.getElementById('characterCard').onclick=document.getElementById('addCharacter').onclick=()=>addElement('character');document.getElementById('backgroundSelect').onchange=event=>mutate('Cambiar fondo',()=>page().background=event.target.value);
  document.querySelectorAll('.layout-option').forEach(button=>button.onclick=()=>mutate('Cambiar viñetas',()=>page().layout=button.dataset.layout));
  document.querySelectorAll('#poseControl button').forEach(button=>button.onclick=()=>{const element=current();if(element)mutate('Cambiar pose',()=>element.pose=button.dataset.pose)});document.getElementById('expressionSelect').onchange=event=>{const element=current();if(element)mutate('Cambiar expresión',()=>element.expression=event.target.value)};
  const continuous=['scaleRange','rotateRange','textInput','fontSize','letterSpacing','bubblePadding'];continuous.forEach(id=>{const input=document.getElementById(id);input.onfocus=input.onpointerdown=()=>controlBefore=JSON.stringify(page());input.onchange=()=>{if(controlBefore){record('Editar propiedad',controlBefore);controlBefore=null}}});
  document.getElementById('scaleRange').oninput=event=>{const element=current();if(element&&!element.locked){element.scale=event.target.value/100;render();scheduleSave()}};document.getElementById('rotateRange').oninput=event=>{const element=current();if(element&&!element.locked){element.rotation=+event.target.value;render();scheduleSave()}};
  document.getElementById('textInput').oninput=event=>{const element=current();if(element&&!element.locked){element.text=event.target.value;render();scheduleSave()}};document.getElementById('fontSize').oninput=event=>{const element=current();if(element&&!element.locked){element.fontSize=+event.target.value;document.getElementById('fontSizeOut').value=event.target.value;render();scheduleSave()}};
  for(const [id,key,parse]of[['fontFamily','fontFamily',String],['textAlign','textAlign',String],['lineHeight','lineHeight',Number],['tailSide','tailSide',String]])document.getElementById(id).onchange=event=>{const element=current();if(element&&!element.locked)mutate('Editar texto',()=>element[key]=parse(event.target.value))};document.getElementById('letterSpacing').oninput=event=>{const element=current();if(element&&!element.locked){element.letterSpacing=+event.target.value;document.getElementById('letterSpacingOut').value=event.target.value;render()}};document.getElementById('bubblePadding').oninput=event=>{const element=current();if(element&&!element.locked){element.bubblePadding=+event.target.value;render()}};
  document.getElementById('flipBtn').onclick=()=>{const element=current();if(element&&!element.locked)mutate('Voltear elemento',()=>element.flip=!element.flip)};document.getElementById('deleteBtn').onclick=removeSelected;
  document.getElementById('undoBtn').onclick=()=>replacePage(history().undo(page()));document.getElementById('redoBtn').onclick=()=>replacePage(history().redo(page()));document.getElementById('newBtn').onclick=addPage;document.getElementById('duplicatePage').onclick=duplicatePage;document.getElementById('movePageLeft').onclick=()=>movePage(-1);document.getElementById('movePageRight').onclick=()=>movePage(1);document.getElementById('deletePage').onclick=deletePage;
  document.getElementById('alignHorizontal').onclick=()=>mutate('Alinear horizontal',()=>{const items=[...selectedIds].map(id=>page().elements.find(e=>e.id===id)).filter(e=>e&&!e.locked);const x=items.reduce((sum,e)=>sum+e.x,0)/items.length;items.forEach(e=>e.x=x)});document.getElementById('alignVertical').onclick=()=>mutate('Alinear vertical',()=>{const items=[...selectedIds].map(id=>page().elements.find(e=>e.id===id)).filter(e=>e&&!e.locked);const y=items.reduce((sum,e)=>sum+e.y,0)/items.length;items.forEach(e=>e.y=y)});
  document.getElementById('bringForward').onclick=()=>mutate('Subir capa',()=>{const element=current(),index=page().elements.indexOf(element);if(index>=0&&index<page().elements.length-1)[page().elements[index],page().elements[index+1]]=[page().elements[index+1],page().elements[index]]});document.getElementById('sendBackward').onclick=()=>mutate('Bajar capa',()=>{const element=current(),index=page().elements.indexOf(element);if(index>0)[page().elements[index],page().elements[index-1]]=[page().elements[index-1],page().elements[index]]});
  document.getElementById('groupLayers').onclick=()=>{if(selectedIds.size<2)return showToast('Selecciona dos o más capas con Shift');mutate('Agrupar capas',()=>{const group=uid('group');for(const element of page().elements)if(selectedIds.has(element.id))element.groupId=group})};
  document.getElementById('projectSelect').onchange=event=>loadProject(event.target.value);document.getElementById('newProject').onclick=createNewProject;document.getElementById('duplicateProject').onclick=duplicateProject;document.getElementById('deleteProject').onclick=deleteProject;document.getElementById('projectName').onchange=event=>{project.name=event.target.value.trim()||'Mi manga';scheduleSave();refreshProjectList()};document.getElementById('importProjectBtn').onclick=()=>document.getElementById('importProjectInput').click();document.getElementById('importProjectInput').onchange=event=>{const file=event.target.files[0];event.target.value='';if(file)importPortableProject(file)};
  document.getElementById('importImageBtn').onclick=()=>document.getElementById('importImageInput').click();document.getElementById('importImageInput').onchange=event=>importImages([...event.target.files]);document.getElementById('assetSearch').oninput=renderAssetLibrary;document.getElementById('importVrmBtn').onclick=()=>document.getElementById('importVrmInput').click();document.getElementById('importVrmInput').onchange=event=>event.target.files[0]&&importVrm(event.target.files[0]);
  document.getElementById('splitPanels').onclick=()=>cyclePanels(1);document.getElementById('mergePanels').onclick=()=>cyclePanels(-1);document.querySelectorAll('[data-template]').forEach(button=>button.onclick=()=>applyTemplate(button.dataset.template));
  bindPageRange('panelGutter',()=>page().panelSettings,'gutter');bindPageRange('panelBorder',()=>page().panelSettings,'border');bindPageRange('panelSlant',()=>page().panelSettings,'slant');bindPageRange('toneDensity',()=>page().toneSettings,'density');bindPageRange('toneScale',()=>page().toneSettings,'scale');bindPageRange('toneAngle',()=>page().toneSettings,'angle');bindPageRange('backgroundOpacity',()=>page(),'backgroundOpacity',value=>+value/100);bindPageRange('backgroundBlur',()=>page(),'backgroundBlur');bindPageRange('backgroundScale',()=>page().backgroundTransform,'scale');bindPageRange('backgroundOffsetX',()=>page().backgroundTransform,'x');bindPageRange('backgroundOffsetY',()=>page().backgroundTransform,'y');document.getElementById('pageBleed').onchange=event=>mutate('Cambiar sangrado',()=>page().panelSettings.bleed=event.target.checked);document.getElementById('backgroundMonochrome').onchange=event=>mutate('Fondo monocromo',()=>page().backgroundMonochrome=event.target.checked);
  const exportModal=document.getElementById('exportModal');document.getElementById('exportBtn').onclick=()=>{exportModal.hidden=false;document.body.style.overflow='hidden';updateExportUi();try{Promise.all(exportPages(exportConfig()).map(preloadPageAssets)).then(updateExportUi).catch(()=>{})}catch{}};document.getElementById('closeExport').onclick=()=>{exportModal.hidden=true;document.body.style.overflow=''};exportModal.addEventListener('click',event=>{if(event.target===exportModal)document.getElementById('closeExport').click()});for(const id of['exportProfile','exportFormat','exportScope','exportScale','exportWidth','exportHeight','exportDpi','exportQuality','exportBleed','exportMarks']){const input=document.getElementById(id);input.oninput=input.onchange=updateExportUi}document.getElementById('exportImages').onclick=()=>runExport(exportImages);document.getElementById('exportPdf').onclick=()=>runExport(exportPdf);document.getElementById('exportProjectFile').onclick=()=>runExport(exportProjectFile);
}

const poseModal=document.getElementById('poseModal');function closePoseModal(){poseModal.hidden=true;document.body.style.overflow='';window.dispatchEvent(new CustomEvent('pose3d:close'))}
document.getElementById('openPose3d').onclick=()=>{if(!current()||current().type!=='character')return;const avatar=project.assets?.find(asset=>asset.id===project.activeVrmAssetId);if(avatar?.blob)window.dispatchEvent(new CustomEvent('pose3d:load-avatar',{detail:{blob:avatar.blob,name:avatar.name}}));poseModal.hidden=false;document.body.style.overflow='hidden';window.dispatchEvent(new CustomEvent('pose3d:open'))};document.getElementById('closePose3d').onclick=closePoseModal;poseModal.addEventListener('click',event=>{if(event.target===poseModal)closePoseModal()});
window.addEventListener('pose3d:apply',event=>{let element=current();if(!element||element.type!=='character'){addElement('character');element=current()}mutate('Aplicar pose 3D',()=>{element.sprite=event.detail.image;element.pose=event.detail.name||'neutral';element.poseSchemaVersion=event.detail.poseSchemaVersion;element.expression='neutral';element.w=300;element.h=460;spriteCache.delete(element.id)});showToast('Pose 3D aplicada')});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){const exportModal=document.getElementById('exportModal');if(!exportModal.hidden){document.getElementById('closeExport').click();return}if(!poseModal.hidden)return closePoseModal();if(drag){replacePage(JSON.parse(drag.before));drag=null;guides=[];showToast('Transformación cancelada')}return}if((event.key==='Delete'||event.key==='Backspace')&&!['TEXTAREA','INPUT'].includes(document.activeElement.tagName))removeSelected();if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?document.getElementById('redoBtn').click():document.getElementById('undoBtn').click()}});
function setZoom(value){zoom=Math.max(.48,Math.min(1.05,value));canvas.style.width=`${600*zoom}px`;canvas.style.height=`${800*zoom}px`;document.getElementById('zoomLabel').textContent=`${Math.round(zoom*100)}%`}
document.getElementById('zoomIn').onclick=()=>setZoom(zoom+.08);document.getElementById('zoomOut').onclick=()=>setZoom(zoom-.08);document.getElementById('fitBtn').onclick=()=>setZoom(innerWidth<520?.54:.82);

async function init(){bindControls();let projects=[];try{projects=await listProjects()}catch(error){console.error(error);showToast('IndexedDB no está disponible')};const activeId=localStorage.getItem('manga-studio-active-project');project=migrateProject(projects.find(item=>item.id===activeId)||projects[0]||(()=>{try{return JSON.parse(localStorage.getItem('manga-studio-state'))}catch{return null}})());await putProject(project);document.getElementById('projectName').value=project.name;await refreshProjectList();setZoom(innerWidth<520?.54:.82);syncPageControls();characterImage.onload=render;window.addEventListener('resize',()=>{if(innerWidth<520&&zoom>.6)setZoom(.54)});setSaveState(projects.length?'Proyecto recuperado ✓':'Proyecto creado ✓')}
init();
