const encoder=new TextEncoder();
function concat(chunks){const total=chunks.reduce((sum,chunk)=>sum+chunk.length,0),result=new Uint8Array(total);let offset=0;for(const chunk of chunks){result.set(chunk,offset);offset+=chunk.length}return result}
const ascii=value=>encoder.encode(value);
const clean=value=>String(value||'Manga Studio').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7e]/g,' ').replace(/[()\\]/g,' ');

export function createJpegPdf(pages,{title='Manga Studio'}={}){
  if(!pages.length)throw new Error('El PDF necesita al menos una página');const count=pages.length,infoId=3+count*3,objects=new Array(infoId+1);objects[1]=ascii('<< /Type /Catalog /Pages 2 0 R >>');const kids=[];
  pages.forEach((page,index)=>{const pageId=3+index*3,imageId=pageId+1,contentId=pageId+2,widthPt=page.width/page.dpi*72,heightPt=page.height/page.dpi*72,kid=`${pageId} 0 R`;kids.push(kid);objects[pageId]=ascii(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${widthPt.toFixed(3)} ${heightPt.toFixed(3)}] /Resources << /XObject << /Im0 ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`);const jpeg=page.bytes instanceof Uint8Array?page.bytes:new Uint8Array(page.bytes),imageHead=ascii(`<< /Type /XObject /Subtype /Image /Width ${page.width} /Height ${page.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`);objects[imageId]=concat([imageHead,jpeg,ascii('\nendstream')]);const command=ascii(`q ${widthPt.toFixed(3)} 0 0 ${heightPt.toFixed(3)} 0 0 cm /Im0 Do Q`);objects[contentId]=concat([ascii(`<< /Length ${command.length} >>\nstream\n`),command,ascii('\nendstream')])});
  objects[2]=ascii(`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${count} >>`);objects[infoId]=ascii(`<< /Title (${clean(title)}) /Creator (Manga Studio 0.7.5) >>`);const chunks=[ascii('%PDF-1.4\n%MangaStudio\n')],offsets=new Array(infoId+1).fill(0);let length=chunks[0].length;for(let id=1;id<=infoId;id++){offsets[id]=length;const object=concat([ascii(`${id} 0 obj\n`),objects[id],ascii('\nendobj\n')]);chunks.push(object);length+=object.length}const xrefOffset=length,recordEnd=Uint8Array.of(32,10),xrefChunks=[ascii(`xref\n0 ${infoId+1}\n0000000000 65535 f`),recordEnd];for(const offset of offsets.slice(1))xrefChunks.push(ascii(`${String(offset).padStart(10,'0')} 00000 n`),recordEnd);xrefChunks.push(ascii(`trailer\n<< /Size ${infoId+1} /Root 1 0 R /Info ${infoId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`));chunks.push(concat(xrefChunks));return concat(chunks)}
