import{svgLooksSafe,validateAssetFile}from'./asset-validation.js';

export const PORTABLE_FORMAT_VERSION=1;
export const MAX_PORTABLE_BYTES=100*1024*1024;
export const MAX_UNPACKED_BYTES=250*1024*1024;
const encoder=new TextEncoder(),decoder=new TextDecoder();
const crcTable=Uint32Array.from({length:256},(_,index)=>{let value=index;for(let bit=0;bit<8;bit++)value=value&1?0xedb88320^(value>>>1):value>>>1;return value>>>0});

function crc32(bytes){let crc=0xffffffff;for(const byte of bytes)crc=crcTable[(crc^byte)&255]^(crc>>>8);return(crc^0xffffffff)>>>0}
function concat(chunks){const size=chunks.reduce((sum,chunk)=>sum+chunk.length,0),result=new Uint8Array(size);let offset=0;for(const chunk of chunks){result.set(chunk,offset);offset+=chunk.length}return result}
function header(size){return new Uint8Array(size)}
function view(bytes){return new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength)}

export function zipEncode(entries){const locals=[],centrals=[];let offset=0;for(const[name,value]of Object.entries(entries)){if(!name||name.includes('..')||name.includes('\\')||name.startsWith('/'))throw new Error('Ruta ZIP inválida');const filename=encoder.encode(name),data=value instanceof Uint8Array?value:new Uint8Array(value),crc=crc32(data),local=header(30+filename.length),lv=view(local);lv.setUint32(0,0x04034b50,true);lv.setUint16(4,20,true);lv.setUint16(6,0x800,true);lv.setUint32(14,crc,true);lv.setUint32(18,data.length,true);lv.setUint32(22,data.length,true);lv.setUint16(26,filename.length,true);local.set(filename,30);locals.push(local,data);const central=header(46+filename.length),cv=view(central);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,crc,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,filename.length,true);cv.setUint32(42,offset,true);central.set(filename,46);centrals.push(central);offset+=local.length+data.length}const centralData=concat(centrals),end=header(22),ev=view(end),count=centrals.length;ev.setUint32(0,0x06054b50,true);ev.setUint16(8,count,true);ev.setUint16(10,count,true);ev.setUint32(12,centralData.length,true);ev.setUint32(16,offset,true);return concat([...locals,centralData,end])}

export function zipDecode(input){const bytes=input instanceof Uint8Array?input:new Uint8Array(input),entries={};let offset=0,total=0,count=0;while(offset+4<=bytes.length&&view(bytes.subarray(offset,offset+4)).getUint32(0,true)===0x04034b50){if(offset+30>bytes.length)throw new Error('Paquete ZIP truncado');const hv=view(bytes.subarray(offset,offset+30)),flags=hv.getUint16(6,true),method=hv.getUint16(8,true),crc=hv.getUint32(14,true),packed=hv.getUint32(18,true),size=hv.getUint32(22,true),nameLength=hv.getUint16(26,true),extraLength=hv.getUint16(28,true);if(flags&8)throw new Error('ZIP con descriptor no compatible');if(method!==0||packed!==size)throw new Error('El proyecto debe usar almacenamiento ZIP sin compresión');const nameStart=offset+30,dataStart=nameStart+nameLength+extraLength,dataEnd=dataStart+size;if(dataEnd>bytes.length)throw new Error('Archivo ZIP truncado');const name=decoder.decode(bytes.subarray(nameStart,nameStart+nameLength));if(!name||name.includes('..')||name.includes('\\')||name.startsWith('/'))throw new Error('Ruta insegura en el paquete');if(Object.hasOwn(entries,name))throw new Error('El paquete contiene rutas duplicadas');if(++count>10000)throw new Error('El paquete contiene demasiados archivos');const data=bytes.slice(dataStart,dataEnd);if(crc32(data)!==crc)throw new Error(`CRC inválido: ${name}`);total+=data.length;if(total>MAX_UNPACKED_BYTES)throw new Error('El proyecto descomprimido supera 250 MB');entries[name]=data;offset=dataEnd}if(!Object.keys(entries).length)throw new Error('El archivo no contiene un proyecto portable');return entries}

async function sha256(bytes){const hash=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(hash)].map(value=>value.toString(16).padStart(2,'0')).join('')}
function dataUrlToBytes(dataUrl){const comma=dataUrl.indexOf(',');if(comma<0)throw new Error('Recurso embebido inválido');const binary=atob(dataUrl.slice(comma+1)),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return bytes}
function bytesToDataUrl(bytes,mime){let binary='';for(let index=0;index<bytes.length;index+=0x8000)binary+=String.fromCharCode(...bytes.subarray(index,index+0x8000));return`data:${mime};base64,${btoa(binary)}`}
function extension(mime,kind){if(kind==='vrm')return'vrm';return{'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/svg+xml':'svg'}[mime]||'bin'}

export async function createPortableProject(project,appVersion='0.7.0'){
  const portable=structuredClone(project),entries={},checksums={};portable.assets=[];
  for(const asset of project.assets||[]){const stored={...asset},path=`assets/${asset.id}.${extension(asset.mime,asset.kind)}`;let bytes;if(asset.kind==='image')bytes=dataUrlToBytes(asset.dataUrl);else if(asset.kind==='vrm')bytes=new Uint8Array(await asset.blob.arrayBuffer());else continue;delete stored.dataUrl;delete stored.blob;stored.file=path;stored.size=bytes.length;portable.assets.push(stored);entries[path]=bytes;checksums[path]=await sha256(bytes)}
  const projectBytes=encoder.encode(JSON.stringify(portable));entries['project.json']=projectBytes;checksums['project.json']=await sha256(projectBytes);
  entries['manifest.json']=encoder.encode(JSON.stringify({format:'manga-studio-project',formatVersion:PORTABLE_FORMAT_VERSION,appVersion,documentSchemaVersion:project.schemaVersion,createdAt:new Date().toISOString(),checksums}));
  return zipEncode(entries);
}

export async function readPortableProject(input){
  const bytes=input instanceof Uint8Array?input:new Uint8Array(input);if(bytes.length>MAX_PORTABLE_BYTES)throw new Error('El proyecto supera el límite de 100 MB');const entries=zipDecode(bytes);if(!entries['manifest.json']||!entries['project.json'])throw new Error('Faltan el manifiesto o el proyecto');let manifest,project;try{manifest=JSON.parse(decoder.decode(entries['manifest.json']));project=JSON.parse(decoder.decode(entries['project.json']))}catch{throw new Error('El manifiesto o el proyecto no contienen JSON válido')}if(manifest.format!=='manga-studio-project'||manifest.formatVersion!==PORTABLE_FORMAT_VERSION)throw new Error('Versión de proyecto portable no compatible');const declared=new Set(['manifest.json',...Object.keys(manifest.checksums||{})]);if(Object.keys(entries).some(path=>!declared.has(path)))throw new Error('El paquete contiene archivos no declarados');for(const[path,expected]of Object.entries(manifest.checksums||{})){if(!entries[path]||await sha256(entries[path])!==expected)throw new Error(`Integridad inválida: ${path}`)}if(!Array.isArray(project.pages)||!Array.isArray(project.assets))throw new Error('Estructura de proyecto inválida');for(const page of project.pages){if(page.thumbnail&&!/^data:image\/jpeg;base64,/i.test(page.thumbnail))throw new Error('Miniatura de página no válida');for(const element of page.elements||[])if(element.sprite&&!/^data:image\/png;base64,/i.test(element.sprite))throw new Error('Captura de personaje no válida')}
  for(const asset of project.assets){if(!asset.file||!entries[asset.file])throw new Error(`Falta el recurso ${asset.name||asset.id}`);const data=entries[asset.file],file={name:asset.file.split('/').at(-1),type:asset.mime,size:data.length},validation=validateAssetFile(file,asset.kind==='vrm'?'vrm':'image');if(!validation.ok)throw new Error(validation.error);if(asset.kind==='image'){if(asset.mime==='image/svg+xml'&&!svgLooksSafe(decoder.decode(data)))throw new Error('El proyecto contiene un SVG inseguro');asset.dataUrl=bytesToDataUrl(data,asset.mime)}else if(asset.kind==='vrm'){if(data.length<12||view(data.subarray(0,12)).getUint32(0,true)!==0x46546c67)throw new Error('El proyecto contiene un VRM inválido');asset.blob=new Blob([data],{type:asset.mime})}delete asset.file;asset.size=data.length}
  return{manifest,project};
}
